//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FinancialMinstry : Ministry
{
	public virtual MinisterOfficeSector MinisterOfficeSector
	{
		get;
		set;
	}

	public virtual PublicTreasurySector PublicTreasurySector
	{
		get;
		set;
	}

	public virtual CustomsSector CustomsSector
	{
		get;
		set;
	}

	public virtual TaxSector TaxSector
	{
		get;
		set;
	}

	public virtual CoinageSector CoinageSector
	{
		get;
		set;
	}

	public virtual PublicBudgetSector PublicBudgetSector
	{
		get;
		set;
	}

}

