//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Sector
{
	public virtual double Budget
	{
		get;
		set;
	}

	public virtual IEnumerable<SectorBranch> SectorBranches
	{
		get;
		set;
	}

	public virtual Human Manager
	{
		get;
		set;
	}

}

